In [3]:
paragraph="Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he rose through the party hierarchy, becoming general secretary in 1998.[b] In 2001, Modi was appointed Chief Minister of Gujarat and elected to the legislative assembly soon after. His administration is considered complicit in the 2002 Gujarat riots,[c] and has been criticised for its management of the crisis. According to official records, a little over 1,000 people were killed, three-quarters of whom were Muslim;"

In [4]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [5]:
import nltk
nltk.download('punkt')
paragraph=nltk.sent_tokenize(paragraph)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\udayk\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [6]:
paragraph

['Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education.',
 'He was introduced to the RSS at the age of eight.',
 'At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so.',
 'Modi became a full-time worker for the RSS in Gujarat in 1971.',
 'The RSS assigned him to the BJP in 1985 and he rose through the party hierarchy, becoming general secretary in 1998.',
 '[b] In 2001, Modi was appointed Chief Minister of Gujarat and elected to the legislative assembly soon after.',
 'His administration is considered complicit in the 2002 Gujarat riots,[c] and has been criticised for its management of the crisis.',
 'According to official records, a little over 1,000 people were killed, three-quarters of whom were Muslim;']

In [7]:
for i in paragraph:
    print(i)
    print("\n")

Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education.


He was introduced to the RSS at the age of eight.


At the age of 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so.


Modi became a full-time worker for the RSS in Gujarat in 1971.


The RSS assigned him to the BJP in 1985 and he rose through the party hierarchy, becoming general secretary in 1998.


[b] In 2001, Modi was appointed Chief Minister of Gujarat and elected to the legislative assembly soon after.


His administration is considered complicit in the 2002 Gujarat riots,[c] and has been criticised for its management of the crisis.


According to official records, a little over 1,000 people were killed, three-quarters of whom were Muslim;




In [8]:
stemmer=PorterStemmer()
stemmer.stem('going')

'go'

In [9]:
stemmer.stem('drinking')
stemmer.stem('history')

'histori'

In [10]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
lemmatizer.lemmatize('going')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\udayk\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


'going'

In [11]:
lemmatizer.lemmatize('history')

'history'

In [12]:
import re
corpus=[]
for i in range(len(paragraph)):
    review=re.sub('[^a-zA-Z]',' ',paragraph[i])
    review=review.lower()
    corpus.append(review)

In [13]:
corpus

['modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education ',
 'he was introduced to the rss at the age of eight ',
 'at the age of     he was married to jashodaben modi  whom he abandoned soon after  only publicly acknowledging her four decades later when legally required to do so ',
 'modi became a full time worker for the rss in gujarat in      ',
 'the rss assigned him to the bjp in      and he rose through the party hierarchy  becoming general secretary in      ',
 ' b  in       modi was appointed chief minister of gujarat and elected to the legislative assembly soon after ',
 'his administration is considered complicit in the      gujarat riots  c  and has been criticised for its management of the crisis ',
 'according to official records  a little over       people were killed  three quarters of whom were muslim ']

In [14]:
nltk.download('stopwords')
stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\udayk\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [15]:
for i in corpus:
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word))

modi
born
rais
vadnagar
northeastern
gujarat
complet
secondari
educ
introduc
rss
age
eight
age
marri
jashodaben
modi
abandon
soon
publicli
acknowledg
four
decad
later
legal
requir
modi
becam
full
time
worker
rss
gujarat
rss
assign
bjp
rose
parti
hierarchi
becom
gener
secretari
b
modi
appoint
chief
minist
gujarat
elect
legisl
assembl
soon
administr
consid
complicit
gujarat
riot
c
criticis
manag
crisi
accord
offici
record
littl
peopl
kill
three
quarter
muslim


In [16]:
for i in corpus:
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatizer.lemmatize(word))

modi
born
raised
vadnagar
northeastern
gujarat
completed
secondary
education
introduced
r
age
eight
age
married
jashodaben
modi
abandoned
soon
publicly
acknowledging
four
decade
later
legally
required
modi
became
full
time
worker
r
gujarat
r
assigned
bjp
rose
party
hierarchy
becoming
general
secretary
b
modi
appointed
chief
minister
gujarat
elected
legislative
assembly
soon
administration
considered
complicit
gujarat
riot
c
criticised
management
crisis
according
official
record
little
people
killed
three
quarter
muslim


In [17]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus)

In [18]:
X[0]

<1x84 sparse matrix of type '<class 'numpy.int64'>'
	with 15 stored elements in Compressed Sparse Row format>

In [19]:
print(len(cv.vocabulary_))
cv.vocabulary_
# shows the indices of the every word in the vector represetation 

84


{'modi': 51,
 'was': 78,
 'born': 15,
 'and': 6,
 'raised': 62,
 'in': 38,
 'vadnagar': 77,
 'northeastern': 53,
 'gujarat': 31,
 'where': 81,
 'he': 33,
 'completed': 17,
 'his': 37,
 'secondary': 68,
 'education': 24,
 'introduced': 39,
 'to': 76,
 'the': 72,
 'rss': 67,
 'at': 10,
 'age': 5,
 'of': 54,
 'eight': 25,
 'married': 49,
 'jashodaben': 42,
 'whom': 82,
 'abandoned': 0,
 'soon': 71,
 'after': 4,
 'only': 56,
 'publicly': 60,
 'acknowledging': 2,
 'her': 34,
 'four': 28,
 'decades': 22,
 'later': 44,
 'when': 80,
 'legally': 45,
 'required': 64,
 'do': 23,
 'so': 70,
 'became': 11,
 'full': 29,
 'time': 75,
 'worker': 83,
 'for': 27,
 'assigned': 9,
 'him': 36,
 'bjp': 14,
 'rose': 66,
 'through': 74,
 'party': 58,
 'hierarchy': 35,
 'becoming': 12,
 'general': 30,
 'secretary': 69,
 'appointed': 7,
 'chief': 16,
 'minister': 50,
 'elected': 26,
 'legislative': 46,
 'assembly': 8,
 'administration': 3,
 'is': 40,
 'considered': 19,
 'complicit': 18,
 'riots': 65,
 'has': 32

In [20]:
corpus[0]

'modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education '

In [21]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]],
      dtype=int64)

In [22]:
import re
corpus=[]
for i in range(len(paragraph)):
    review=re.sub('[^a-zA-Z]',' ',paragraph[i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [23]:
corpus

['modi born raised vadnagar northeastern gujarat completed secondary education',
 'introduced r age eight',
 'age married jashodaben modi abandoned soon publicly acknowledging four decade later legally required',
 'modi became full time worker r gujarat',
 'r assigned bjp rose party hierarchy becoming general secretary',
 'b modi appointed chief minister gujarat elected legislative assembly soon',
 'administration considered complicit gujarat riot c criticised management crisis',
 'according official record little people killed three quarter muslim']


from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus)

In [34]:
# Bag of Words
from sklearn.feature_extraction.text import CountVectorizer 
cv=CountVectorizer() 
X=cv.fit_transform(corpus)

In [35]:
print(len(cv.vocabulary_))
cv.vocabulary_

57


{'modi': 37,
 'born': 11,
 'raised': 45,
 'vadnagar': 55,
 'northeastern': 39,
 'gujarat': 25,
 'completed': 13,
 'secondary': 50,
 'education': 19,
 'introduced': 27,
 'age': 4,
 'eight': 20,
 'married': 35,
 'jashodaben': 28,
 'abandoned': 0,
 'soon': 52,
 'publicly': 43,
 'acknowledging': 2,
 'four': 22,
 'decade': 18,
 'later': 30,
 'legally': 31,
 'required': 47,
 'became': 8,
 'full': 23,
 'time': 54,
 'worker': 56,
 'assigned': 7,
 'bjp': 10,
 'rose': 49,
 'party': 41,
 'hierarchy': 26,
 'becoming': 9,
 'general': 24,
 'secretary': 51,
 'appointed': 5,
 'chief': 12,
 'minister': 36,
 'elected': 21,
 'legislative': 32,
 'assembly': 6,
 'administration': 3,
 'considered': 15,
 'complicit': 14,
 'riot': 48,
 'criticised': 17,
 'management': 34,
 'crisis': 16,
 'according': 1,
 'official': 40,
 'record': 46,
 'little': 33,
 'people': 42,
 'killed': 29,
 'three': 53,
 'quarter': 44,
 'muslim': 38}

In [36]:
corpus[0]

'modi born raised vadnagar northeastern gujarat completed secondary education'

In [37]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=True,ngram_range=(2,3))
#here ngram = (2,3) means it takes possible combinations of 2 and 3 words as a single word and they are kept as columns in the table
X=cv.fit_transform(corpus)
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0]],
      dtype=int64)

In [39]:
print(len(cv.vocabulary_))
cv.vocabulary_

106


{'modi born': 75,
 'born raised': 22,
 'raised vadnagar': 88,
 'vadnagar northeastern': 103,
 'northeastern gujarat': 77,
 'gujarat completed': 43,
 'completed secondary': 26,
 'secondary education': 96,
 'modi born raised': 76,
 'born raised vadnagar': 23,
 'raised vadnagar northeastern': 89,
 'vadnagar northeastern gujarat': 104,
 'northeastern gujarat completed': 78,
 'gujarat completed secondary': 44,
 'completed secondary education': 27,
 'introduced age': 51,
 'age eight': 8,
 'introduced age eight': 52,
 'age married': 9,
 'married jashodaben': 65,
 'jashodaben modi': 53,
 'modi abandoned': 69,
 'abandoned soon': 0,
 'soon publicly': 97,
 'publicly acknowledging': 85,
 'acknowledging four': 4,
 'four decade': 38,
 'decade later': 34,
 'later legally': 57,
 'legally required': 59,
 'age married jashodaben': 10,
 'married jashodaben modi': 66,
 'jashodaben modi abandoned': 54,
 'modi abandoned soon': 70,
 'abandoned soon publicly': 1,
 'soon publicly acknowledging': 98,
 'publicly

In [40]:
#TF-IDF (term frequency - Inverse Document Frequency)
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer()
X=cv.fit_transform(corpus)

In [41]:
X[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.357963  , 0.        , 0.357963  , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.357963  ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.22697736, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.22697736, 0.        , 0.357963  ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.357963  , 0.        , 0.        , 0.        , 0.        ,
        0.357963  , 0.        , 0.        , 0.        , 0.        ,
        0.357963  , 0.        ]])